export const propertyTypes=['apartment','villa','chalet','office','retail','land','building','warehouse','factory','commercial','other'];
export const areas=['zayed','newcairo','october','maadi','heliopolis','alex','coast','capital','gamalon','nasrcity','dokki','tenthramadan'];
export const features=['finished','sea','parking','compound','ready','installments','corner','road','license','garden'];
// Governorate of each district, so a governorate-level buyer request matches properties inside it.
export const governorates:Record<string,string>={zayed:'giza',october:'giza',gamalon:'giza',hadayekoctober:'giza',dokki:'giza',mohandessin:'giza',haram:'giza',newcairo:'cairo',maadi:'cairo',heliopolis:'cairo',nasrcity:'cairo',zamalek:'cairo',shorouk:'cairo',badr:'cairo',madinaty:'cairo',capital:'cairo',shoubra:'cairo',tenthramadan:'sharkia',belbeis:'sharkia',coast:'matrouh',alex:'alexandria',sokhna:'suez',sahlhasheesh:'redsea',somabay:'redsea',makadi:'redsea',damanhour:'beheira',mansoura:'dakahlia'};
export const locationMatches=(wanted:string[],location:string)=>wanted.includes(location)||wanted.includes('gov_'+governorates[location])||(location==='gamalon'&&wanted.includes('october'));
export const residential=['apartment','villa','chalet'];
export interface PropertyRequest { intent:'buy'; type:string; locations:string[]; budgetMin:number; budgetMax:number; sizeMin:number; sizeMax:number; bedrooms:number; bathrooms:number; floor:string; features:string[]; notes:string; name:string; phone:string; consent:boolean; broker:boolean; company:string; }
export const initialRequest:PropertyRequest={intent:'buy',type:'',locations:[],budgetMin:5000000,budgetMax:15000000,sizeMin:150,sizeMax:250,bedrooms:0,bathrooms:0,floor:'',features:[],notes:'',name:'',phone:'',consent:false,broker:false,company:''};
export const validation={phone:/^(?:\+?20|0)?1[0125]\d{8}$/,maxBudget:200000000,minName:2};
export function validateStep(s:number,r:PropertyRequest):string|null {if(s===1&&!r.type)return 'error';if(s===2&&!r.locations.length)return 'error';if(s===3&&(!r.budgetMin||r.budgetMax<r.budgetMin))return 'budgetError';if(s===4&&(r.sizeMin<=0||!Number.isFinite(r.sizeMin)||!Number.isFinite(r.sizeMax)||r.sizeMax<r.sizeMin||r.bedrooms<0||r.bathrooms<0))return 'error';if(s===6&&(r.name.trim().length<validation.minName||!validation.phone.test(r.phone.replace(/[\s-]/g,''))||!r.consent))return 'phoneError';if(s===6&&r.broker&&r.company.trim().length<2)return 'companyError';return null;}
// A public buyer request. Live HubSpot posts set `live`; 0 for size or max budget means "not specified" / "no upper limit".
export interface Demand {id:string;type:string;locations:string[];min:number;max:number;sizeMin:number;sizeMax:number;features:string[];matches?:number;posted:string;note:string;bedrooms?:number;bathrooms?:number;approx?:boolean;band?:string;createdAt?:string;updatedAt?:string;live?:boolean;}
export const requests:Demand[]=[
{id:'BM-26041',type:'land',locations:['zayed'],min:50000000,max:70000000,sizeMin:4000,sizeMax:5000,features:['road','license'],matches:12,posted:'posted1',note:'note1'},
{id:'BM-26040',type:'villa',locations:['newcairo'],min:18000000,max:25000000,sizeMin:350,sizeMax:500,features:['garden','compound','finished'],matches:8,posted:'posted2',note:'note2',bedrooms:4,bathrooms:3},
{id:'BM-26039',type:'office',locations:['capital','newcairo'],min:6000000,max:10000000,sizeMin:120,sizeMax:200,features:['parking','finished'],matches:6,posted:'posted3',note:'note3'},
{id:'BM-26038',type:'apartment',locations:['maadi'],min:7000000,max:12000000,sizeMin:180,sizeMax:250,features:['finished','parking'],matches:9,posted:'posted4',note:'note4',bedrooms:3,bathrooms:2},
{id:'BM-26037',type:'land',locations:['zayed','october'],min:45000000,max:68000000,sizeMin:3500,sizeMax:4500,features:['license','corner'],matches:5,posted:'posted5',note:'note5'},
{id:'BM-26036',type:'land',locations:['zayed'],min:60000000,max:85000000,sizeMin:4000,sizeMax:6000,features:['road'],matches:4,posted:'posted6',note:'note6'}];
export interface SellerProperty {type:string;location:string;size:number;price:number;bedrooms:number;bathrooms:number;features:string[];notes:string;}
export const defaultSeller:SellerProperty={type:'land',location:'zayed',size:4200,price:65000000,bedrooms:0,bathrooms:0,features:['road','license'],notes:''};
export function matchRequests(p:SellerProperty,demand:Demand[]=requests){return demand.map(r=>{const checks={type:r.type===p.type,location:locationMatches(r.locations,p.location),size:!r.sizeMin||(p.size>=r.sizeMin&&p.size<=r.sizeMax),budget:p.price>=r.min*(r.approx?.85:1)&&(!r.max||p.price<=r.max*(r.approx?1.15:1)),bedrooms:!r.bedrooms||p.bedrooms>=r.bedrooms,bathrooms:!r.bathrooms||p.bathrooms>=r.bathrooms};const fit=r.features.filter(f=>p.features.includes(f)).length/Math.max(1,r.features.length);const score=Math.round(Number(checks.type)*25+Number(checks.location)*25+Number(checks.size)*15+Number(checks.budget)*20+fit*10+Number(checks.bedrooms)*2.5+Number(checks.bathrooms)*2.5);return {request:r,checks,score};}).filter(x=>x.checks.type&&x.checks.location&&x.score>=65).sort((a,b)=>b.score-a.score);}
